---
functional:
  - Пользователи могут регистрироваться
  - Пользователи могут аутентифицироваться
  - Зарегистрированные пользователи могут создавать и редактировать свой профиль
  - Пользователи могут создавать задачи для решения
  - Пользователи могут создавать игровую сессию и решать задачи
  - Для решения задач можно использовать различные языки программирования
  - Платформа предоставляет чат для взаимодействия c другими участниками
  - Пользователь должен иметь возможность выбирать параметры игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Наличие темной темы
  - Поддержка нескольких языков